const arrayDamage = [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 4, 4, 6, 0, 0, 0, 0, 0, 0, 0, 0, 5, 5, 7, 7]
const FuncDictDamage = ({x}) => {
    const dictDamage = {
        0: ['Your opponent missed the attack!'],
        1: [`It was effective! You lose ${x} HP.`],
        2: [`It was effective! <b>CRITICAL HIT!</b> You lose ${x} HP.`],
        3: [`It was ultra effective! You lose ${x} HP.`],
        4: [`It was super effective! <b>CRITICAL HIT!</b> You lose ${x} HP.`],
        5: [`It was effective! You lose ${x} HP. You flinched! Opponent attacks again.`],
        6: [`It was ultra effective! <b>CRITICAL HIT!</b> You lose ${x} HP.`],
        7: ['COUNTER! You take no damage and have an extra attack!'],
        8: ['Damage <b>BLOCKED</b>'],
    }
    return dictDamage
}
const itemDict = {
    0: ['You found nothing!'],
    1: ['You found a Potion and recovered 1 HP!'],
    2: ['You found a Super Potion and recovered 2 HP!'],
    3: ['You found a Hyper Potion and recovered 3 HP!'],
    4: ['You found a Flame Orb and lost 3 HP.'],
    5: ['You found a Quick Claw and can attack twice!'],
    6: ['You found X-Defense. Any damage you\'d take in next turn will be reduced by 2.'],
    7: ['You found X-Attack. Any damage you\'d cause in next turn will be increased by 2.'],
}

const dictAttack = {
    0: ['Typhlosion used Flamethrower'],
    1: ['Breloom used Energy Ball'],
    2: ['Noctowl used Fly'],
    3: ['Hydreigon used Tri-Attack'],
    4: ['Shedinja used Confuse Ray'],
    5: ['Cinccino used Tail Slap'],
    6: ['Leavanny used Razor Leaf'],
    7: ['Electrode used Explosion'],
    8: ['Vulpix and Ninetales used Flamethrower'],
    9: ['Eevee used Iron Tail'],
    10: ['Gallade used Close Combat'],
    11: ['Articuno used Ice Beam'],
    12: ['Glaceon used Blizzard'],
    13: ['Greninja used Water Shuriken'],
    14: ['Milotic used Water Pulse'],
    15: ['Marowak used Bonemerang'],
    16: ['Alakazam used Telekinesis'],
    17: ['Glameow used Shadow Claw'],
    18: ['Buizel used Water Pulse'],
    19: ['Pikachu used Volt Tackle'],
    20: ['Eevee used Trump Card'],
    21: ['Garbodor used Acid Spray'],
    22: ['Gyarados used Hyper Beam'],
    23: ['Eevee used Quick Attack'],
    24: ['Keldeo used Water Gun'],
    25: ['Vaporeon used Bubble'],
    26: ['Mewtwo used Swift'],
    27: ['Mewtwo used Shadow Ball'],
    28: ['Machamp used Brick Break'],
    29: ['Rayquaza used Ice Beam'],
    30: ['Pikachu used Quick Attack'],
    31: ['Lucario used Bone Rush'],
    32: ['Bulbasaur used Solar Beam'],
    33: ['Lucario used Metal Claw'],
    34: ['Rayquaza used Hyper Beam'],
    35: ['Volcanion used Steam Eruption'],
    36: ['Deoxys used Psycho Boost'],
    37: ['Slugma, Rapidash, Magmortar and Heatran used Flamethrower'],
    38: ['Rayquaza used Dragon Ascent'],
    39: ['Pikachu used Electric Ball'],
    40: ['Groudon used Hyper Beam'],
    41: ['Mega Charizard X used Dragon Claw'],
    42: ['Pikachu used Quick Attack'],
    43: ['Clefairy used Metronome'],
    44: ['Dewgong used Aurora Beam'],
    45: ['Magearna used Fleur Cannon'],
    46: ['Giratina used Stomp'],
    47: ['Magikarp used Splash'],
    48: ['Scizor used Metal Claw'],
    49: ['Charizard used Heat Wave'],
    50: ['Liepard used Shadow Ball'],
    51: ['Bisharp used Iron Head'],
    52: ['Golem used Rollout'],
    53: ['Gengar used Hypnosis'],
    54: ['Bayleef used Vine Whip'],
    55: ['Mightyena used Shadow Ball'],
    56: ['Ninetales used Fire Blast'],
    57: ['Mandibuzz used Shadow Ball'],
    58: ['Charizard used Flamethrower'],
    59: ['Espeon used Hidden Power'],
    60: ['Arceus used Hyper Beam'],
    61: ['Blastoise used Hydro Pump'],
    62: ['Mega Charizard X used Fire Blast'],
    63: ['Hoopa used Hyperspace Hole'],
    64: ['Scyther used Fury Cutter'],
    65: ['Greninja used Water Shuriken'],
    66: ['Lucario used Swords Dance'],
    67: ['Articuno used Ice Beam'],
    68: ['Mr. Mime used Reflect'],
    69: ['Moltres used Flamethrower'],
    70: ['Greninja used Double Team'],
    71: ['Beedril used Twineedle'],
    72: ['Serperior used Dragon Tail'],
    73: ['Mew used Psycho Boost'],
    74: ['Hydreigon used Ice Beam'],
    75: ['Gengar used Hyper Beam'],
    76: ['Jolteon used Thunderbolt'],
    77: ['Lucario used Aura Sphere'],
    78: ['Infernape used Flare Blitz'],
    79: ['Landorus used Extrasensory'],
    80: ['Gliscor used X-Scissor'],
    81: ['Venusaur used Razor Leaf'],
    82: ['Noivern used Air Slash'],
    83: ['Galvantula used Electro Web'],
    84: ['Yanmega used Sonic Boom'],
    85: ['Sawsbuck used Horn Leech'],
    86: ['Dragonite used Hyper Beam'],
    87: ['Flygon used Aerial Ace'],
    88: ['Chimecho used Uproar'],
    89: ['Nidoking used Thunderbolt'],
    90: ['Pikachu used Iron Tail'],
    91: ['Zoroark used Ilusion'],
    92: ['Zoroark used Throat Chop'],
    93: ['Shuppet used Night Shade'],
    94: ['Zorua used Scratch'],
    95: ['Celebi used Synthesis'],
    96: ['Bronzor used Iron Defense'],
    97: ['Ninjasks used Shadow Ball'],
    98: ['Tangrowth used Vine Whip'],
    99: ['Suicune used Icy Wind'],
    100: ['Entei used Flamethrower'],
    101: ['Piplup used Water Gun'],
    102: ['Entei used Flare Blitz'],
    103: ['Mamoswine used Ice Shard'],
    104: ['Zoroark used Shadow Claw'],
    105: ['Mismagius used Psychic'],
    106: ['Pikachu used Volt Tackle'],
    107: ['Zoroark used Night Daze'],
    108: ['Alakazam used Psybeam'],
    109: ['Samurott used Sacred Sword'],
    110: ['Dewgong used Ice Beam'],
    111: ['Staraptor used Wing Attack'],
    112: ['Ash-Greninja used Water Shuriken(Melee)'],
    113: ['Hitmoncham used Mega Punch'],
    114: ['Ampharos used Thunder Punch'],
    115: ['Vanillish used Ice Beam'],
    116: ['Weavile used Metal Claw'],
    117: ['Ash-Greninja used Water Shuriken'],
    118: ['Squirtle, Staryu and Starmie used Water Gun'],
    119: ['Reuniclus used Shock Wave'],
    120: ['Sceptile used Crush Claw'],
    121: ['Mega-Alakazam used Psychic'],
    122: ['Armaldo used Ancient Power']
}

module.exports = {
    arrayDamage, FuncDictDamage, itemDict, dictAttack
}
